### ISSUE TITLE
ERROR: Could not build wheels for pyzmq which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by Giovanni-Trivigno** [craigbarratt/hass-pyscript-jupyter#13]
Hi!
I use Home Assistant on a Raspberry Pi4 .
With the following command:

`pip install hass_pyscript_kernel`

I get the following error:

`ERROR: Could not build wheels for pyzmq which use PEP 517 and cannot be installed directly`

Thanks to those who will be able to provide me with support

**Comment by craigbarratt** [comment]
It appears that `pyzmq` that is used by `hass_pyscript_kernel` isn't supported on Raspberry Pi4.  However, `hass_pyscript_kernel` should be installed on the machine that is running the Jupyter client and browser, not on the HASS target.  Which machine (eg, laptop) will you run the Jupyter client and browser?

**Comment by Giovanni-Trivigno** [comment]
Hi!
I run the Jupyter client and browser on a pc desktop (Windows 10)
My browser is Brave
So what should I do?
Tnanks

**Comment by craigbarratt** [comment]
Did you run the `pip` command on your PC desktop Win10, or on Raspberry Pi4?  (You should run the `pip install hass_pyscript_kernel on the Win10 machine.)

The error is that `pyzmq` cannot be installed.  What happens when you run this command:
```
pip install pyzmq
```
If you get the same error, you could try searching for solutions, eg: [this page](https://stackoverflow.com/questions/61365790/error-could-not-build-wheels-for-scipy-which-use-pep-517-and-cannot-be-installe).

**Comment by Giovanni-Trivigno** [comment]
Hi!
Ok, I installed hass_pyscript_kernel on the pc but did not understand how to use it with HA ... :-(

**Comment by craigbarratt** [comment]
To confirm, did it install correctly?

After it's installed, the documentation explains how to configure it, and also how to get debug information if there is an issue.

**Comment by jcisio** [comment]
Thank you for this issue. I got the same error because I tried to install the kernel on my rpi4 (I didn't understand). I think we should add a note about that, even the principle seems trivial for someone.

**Comment by jcisio** [comment]
@Giovanni-Trivigno FWIW it is already documented. Run `jupyter notebook` will open the browser, then create new notebook with hass kernel and you are now in the same environment with your pyscript in HA. It's really useful to test and debug. Without it you have to rely on logger to debug, and because you have to reload pyscrypt after each change it's much less convenient.

**Comment by Giovanni-Trivigno** [comment]
@jcisio :
Hi!
Thank you for your useful intervention.
At the moment my situation is as follows:

![image](https://user-images.githubusercontent.com/33354144/106438983-7c0c5180-6477-11eb-9990-d45b9617da6d.png)

**Comment by craigbarratt** [comment]
I'm not familiar with running python or Jupyter on Windows.  As you can see, `jupyter-notebook` isn't found.

I'd recommend looking for a tutorial about running Jupyter notebook on Windows.  The couple I just looked at suggest it's easiest if you install Anaconda.  Do you have that installed?

**Comment by Giovanni-Trivigno** [comment]
No. I haven't installed it and...
The subject seems too confusing to me to continue to be interested in it.
Thanks anyway

**Comment by jcisio** [comment]
I guess some problem with PATH. The easiest way could be remove them all and reinstall. I once had a similar problem because I have Python installed using Conda last year, then another env created by an IDE, then the Python package from Ubuntu... Because I was (am) not familiar with venv, I remove them all and used the package from the OS and it worked. But it was not Windows.

**Comment by craigbarratt** [comment]
Closing since OP doesn't seem interested in solving their issue.  The docs are updated to explain that `hass_pyscript_kernel` should be installed on the client that is running Jupyter and the browser, not the HASS target. @jcisio - thanks for your help & suggestions!

**Comment by brando90** [comment]
perhaps useful? https://github.com/zeromq/pyzmq/pull/1508

**Comment by brando90** [comment]
temp work around:
```
pip install pyzmq==23.2.1
```

**Comment by brando90** [comment]
perhaps see: https://github.com/zeromq/pyzmq/issues/1764

**Comment by GritLs** [comment]
@brando90 thanks!
my problem is that vscode jupyter failed to start kernal.
I saw that some people on stackoverflow said to uninstall pyzmq because its version is too high, but they all suggested to install 19.0.2, in fact, it is no longer possible, it will produce the same error as yours. 
Just install version 23.2.1 to make jupyter work correctly.
one line command as:
`pip install pyzmq==23.2.1`

**Comment by nixiPython80** [comment]
Please help me to fix this problem, thanks in advance

      DEBUG EXT_SUFFIX '.cp312-win_amd64' '.cp312-win_amd64.pyd'
      ************************************************
      DEBUG EXT_SUFFIX '.cp312-win_amd64' '.cp312-win_amd64.pyd'
      ************************************************
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
